# Generated by Django 2.1.3 on 2018-11-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ket',
            field=models.TextField(default='', verbose_name='Keterangan'),
            preserve_default=False,
        ),
    ]
